package com.mycreat.kiipu.db.bookmark;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.mycreat.kiipu.db.bookmark.model.Template;

import com.mycreat.kiipu.db.bookmark.TemplateDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig templateDaoConfig;

    private final TemplateDao templateDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        templateDaoConfig = daoConfigMap.get(TemplateDao.class).clone();
        templateDaoConfig.initIdentityScope(type);

        templateDao = new TemplateDao(templateDaoConfig, this);

        registerDao(Template.class, templateDao);
    }
    
    public void clear() {
        templateDaoConfig.clearIdentityScope();
    }

    public TemplateDao getTemplateDao() {
        return templateDao;
    }

}
