package com.mycreat.kiipu.db.bookmark.model;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "template".
 */
@Entity(nameInDb = "template")
public class Template {

    @Id(autoincrement = true)
    @Index
    private Long id;

    @NotNull
    @Unique
    @Index
    private String name;

    @NotNull
    private String url;
    private String local_path;
    private Integer version_code;
    private String reserved;

    @Generated
    public Template() {
    }

    public Template(Long id) {
        this.id = id;
    }

    @Generated
    public Template(Long id, String name, String url, String local_path, Integer version_code, String reserved) {
        this.id = id;
        this.name = name;
        this.url = url;
        this.local_path = local_path;
        this.version_code = version_code;
        this.reserved = reserved;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getName() {
        return name;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setName(@NotNull String name) {
        this.name = name;
    }

    @NotNull
    public String getUrl() {
        return url;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUrl(@NotNull String url) {
        this.url = url;
    }

    public String getLocal_path() {
        return local_path;
    }

    public void setLocal_path(String local_path) {
        this.local_path = local_path;
    }

    public Integer getVersion_code() {
        return version_code;
    }

    public void setVersion_code(Integer version_code) {
        this.version_code = version_code;
    }

    public String getReserved() {
        return reserved;
    }

    public void setReserved(String reserved) {
        this.reserved = reserved;
    }

}
